language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jekyll-utils' ]; then cd .. && eval "mv $currentfolder generator-jekyll-utils" && cd generator-jekyll-utils; fi

